--USE test_task;

--SELECT e.FIRST_NAME, e.LAST_NAME, e.EMAIL, e.PHONE_NUMBER
--FROM EMPLOYEES AS e
--    JOIN EMPLOYEES m ON e.MANAGER_ID = m.EMPLOYEE_ID
--    JOIN JOBS j ON j.JOB_ID = e.JOB_ID
--WHERE MONTH(m.HIRE_DATE) = 11;


--USE test_task;

--SELECT js.JOB_TITLE
--FROM JOBS AS js


--DROP DATABASE test_task;